# Generated by Django 6.1.1 on 2026-10-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=100)),
                ('site_id', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
